name: Matrix build demo

on:
  push:
  workflow_dispatch:

jobs:
  matrix_job_demo:
    name: Matrix job demo
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        version: [10, 12, 14]
        os: [ubuntu-latest, windows-latest]
    
    steps:
    - run: echo 'Hello from ${{ matrix.os }} - ${{ matrix.version }}'
