name: Techtalk demo dinsdag avond

on:
  push:
  
env:
  foo: 'Foo value'

jobs:
  say-something-job:
    name: 'My say something job'
    runs-on: ubuntu-latest
    
    steps:
      - run: echo 'Hello there ${{ env.foo }}' 
      - run: echo 'My ref is ${{ github.ref }}'
      - run: echo 'My secret is ${{ secrets.ONS_DB_WACHTWOORD }}'
      
  say-something-job2:
    name: 'My say something job 2'
    runs-on: ubuntu-latest
    
    needs: say-something-job

    steps:
      - run: echo 'Hello there ${{ env.foo }}' 
      
      
    
