name: Techtalk demo dinsdag avond

on:
  push:
  
jobs:
  say-something-job:
    name: 'My say something job'
    runs-on: ubuntu-latest
    
    steps:
      - run: echo 'Hello there' 
      
      
    
